import {redirect} from 'next/navigation';import {viewer} from '@/lib/supabase';import {createCourse,createModule,createLesson,grantAccess,reviewTransfer,saveSettings,sendMessage} from '@/app/actions';
export const dynamic='force-dynamic';
export default async function Admin({searchParams}:{searchParams:Promise<{error?:string}>}){const {db,user,profile}=await viewer();if(!user)redirect('/login?next=/admin');if(!['super_admin','admin','support','instructor'].includes(profile?.role))redirect('/dashboard');
 const error=(await searchParams).error;
 const errorMessage=error==='slug-duplicado'?'Ese slug ya existe. Usa uno diferente.':error==='sin-permiso'?'Tu usuario no tiene permisos para realizar esta acción.':error==='error-curso'?'Supabase no pudo guardar el curso. Revisa la tabla courses y sus políticas.':error==='portada-invalida'?'La portada debe ser JPG, PNG o WebP y pesar máximo 5 MB.':error==='portada-subida'?'No se pudo subir la portada. Revisa el bucket course-covers y sus políticas.':error==='curso-con-datos'?'No se puede borrar porque el curso tiene transferencias o pagos relacionados.':error==='error-borrar-curso'?'No se pudo borrar el curso. Revisa sus datos relacionados.':null;
 const canEdit=['super_admin','admin','instructor'].includes(profile?.role),canManage=['super_admin','admin'].includes(profile?.role);
 const [{data:users},{data:courses},{data:modules},{data:transfers},{data:settings},{data:messages},{data:enrollments}]=await Promise.all([
 db.from('profiles').select('id,email,full_name,role,created_at').order('created_at',{ascending:false}).limit(100),db.from('courses').select('id,title,slug,description,cover_url,level,price,paypal_usd_price,published').order('created_at',{ascending:false}),db.from('modules').select('id,course_id,title,position').order('position'),db.from('bank_transfers').select('id,user_id,course_id,bank,reference,receipt_path,amount,status,created_at').order('created_at',{ascending:false}).limit(100),db.from('settings').select('key,value'),db.from('messages').select('id,body,sender_id,recipient_id,created_at').order('created_at',{ascending:false}).limit(30),db.from('enrollments').select('user_id,course_id,expires_at,status').limit(200)
 ]);
 const config=Object.fromEntries((settings||[]).map(s=>[s.key,s.value]));
 const signed=await Promise.all((transfers||[]).map(async t=>({id:t.id,url:(await db.storage.from('receipts').createSignedUrl(t.receipt_path,300)).data?.signedUrl})));
 const receiptUrls=Object.fromEntries(signed.map(s=>[s.id,s.url]));
 return <main className="shell layout"><aside className="sidebar"><a href="#resumen">Resumen</a><a href="#crm">CRM</a><a href="#academia">Cursos</a><a href="#ventas">Transferencias</a><a href="#chat">Chat</a><a href="#config">Configuración</a></aside><div className="dashboard stack"><div id="resumen"><span className="eyebrow">Administración</span><h1 style={{fontSize:44}}>Panel de control</h1><p>Bienvenido, {profile?.full_name||profile?.email}.</p></div><div className="stats"><div className="card stat"><span className="meta">Usuarios</span><strong>{users?.length||0}</strong></div><div className="card stat"><span className="meta">Cursos</span><strong>{courses?.length||0}</strong></div><div className="card stat"><span className="meta">Transferencias pendientes</span><strong>{transfers?.filter(t=>t.status==='pending').length||0}</strong></div></div>
 <section id="crm" className="card"><h2>CRM · Usuarios</h2><p className="tiny">Se muestran los 100 registros más recientes.</p><div className="tablewrap"><table className="table"><thead><tr><th>Nombre</th><th>Correo</th><th>Rol</th><th>Acceso</th></tr></thead><tbody>{users?.map(u=><tr key={u.id}><td>{u.full_name||'—'}</td><td>{u.email}</td><td>{u.role}</td><td>{enrollments?.filter(e=>e.user_id===u.id).map(e=><div key={e.course_id}>{courses?.find(c=>c.id===e.course_id)?.title||'Curso'} · {e.expires_at?new Date(e.expires_at).toLocaleDateString('es-DO'):'Ilimitado'}</div>)}</td></tr>)}</tbody></table></div>{canManage&&<><hr className="divider"/><h3>Otorgar o extender acceso</h3><form className="cols" action={grantAccess}><label>Estudiante<select name="user_id" required>{users?.filter(u=>u.role==='student').map(u=><option value={u.id} key={u.id}>{u.email}</option>)}</select></label><label>Curso<select name="course_id" required>{courses?.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select></label><label>Días adicionales<input type="number" name="days" defaultValue={90} min={1} max={3650} required/></label><button>Guardar acceso</button></form></>}</section>
 <section id="academia" className="card"><h2>Academia · Cursos</h2>{courses?.map(c=><div key={c.id} className="row" style={{padding:'11px 0',borderBottom:'1px solid var(--line)'}}><div><b>{c.title}</b><br/><span className="meta">/{c.slug} · RD$ {c.price}</span></div><span className={'badge '+(c.published?'':'dim')}>{c.published?'Publicado':'Borrador'}</span></div>)}{canEdit&&<div className="cols" style={{marginTop:28}}><div><h3>Nuevo curso</h3><form action={createCourse}><label>Título<input name="title" required/></label><label>Slug (minúsculas y guiones)<input name="slug" pattern="[a-z0-9-]+" required/></label><label>Descripción<textarea name="description" minLength={10} required/></label><label>Precio RD$<input name="price" type="number" min="0" step="0.01" required/></label><label>Nivel<input name="level" defaultValue="Inicial" required/></label><label>Precio PayPal USD (opcional)<input name="paypal_usd_price" type="number" min="0.01" step="0.01"/></label><label className="inline"><input type="checkbox" name="published" style={{width:'auto'}}/> Publicar curso</label><button>Crear curso</button></form></div><div className="stack"><div><h3>Nuevo módulo</h3><form action={createModule}><label>Curso<select name="course_id" required>{courses?.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select></label><label>Título<input name="title" required/></label><label>Orden<input name="position" type="number" defaultValue={0}/></label><button>Crear módulo</button></form></div><div><h3>Nueva lección</h3><form action={createLesson}><label>Módulo<select name="module_id" required>{modules?.map(m=><option value={m.id} key={m.id}>{courses?.find(c=>c.id===m.course_id)?.title} / {m.title}</option>)}</select></label><label>Título<input name="title" required/></label><label>URL segura del reproductor<input name="video_url" type="url" placeholder="https://player.vimeo.com/video/…"/></label><label>Contenido<textarea name="body" rows={4}/></label><label>Orden<input name="position" type="number" defaultValue={0}/></label><label className="inline"><input type="checkbox" name="published" style={{width:'auto'}}/> Publicar clase</label><button>Crear lección</button></form></div></div></div>}</section>
 <section id="ventas" className="card"><h2>Transferencias</h2>{transfers?.length?<div className="tablewrap"><table className="table"><thead><tr><th>Estudiante / Curso</th><th>Monto y referencia</th><th>Comprobante</th><th>Decisión</th></tr></thead><tbody>{transfers.map(t=><tr key={t.id}><td>{users?.find(u=>u.id===t.user_id)?.email||t.user_id}<br/>{courses?.find(c=>c.id===t.course_id)?.title||t.course_id}</td><td>RD$ {t.amount}<br/>{t.bank} · {t.reference}</td><td>{receiptUrls[t.id]?<a href={receiptUrls[t.id]} target="_blank" rel="noreferrer">Abrir ↗</a>:'No disponible'}</td><td>{t.status==='pending'&&canManage?<div className="inline"><form action={reviewTransfer}><input type="hidden" name="transfer_id" value={t.id}/><button name="decision" value="approve">Aprobar</button></form><form action={reviewTransfer}><input type="hidden" name="transfer_id" value={t.id}/><button className="ghost" name="decision" value="reject">Rechazar</button></form></div>:t.status}</td></tr>)}</tbody></table></div>:<p>No hay comprobantes enviados.</p>}</section>
 <section id="chat" className="card"><h2>Mensajes</h2>{messages?.map(m=><div className="card" key={m.id} style={{marginBottom:10}}><span className="meta">{users?.find(u=>u.id===m.sender_id)?.email||'Usuario'} · {new Date(m.created_at).toLocaleString('es-DO')}</span><p>{m.body}</p>{m.sender_id!==user.sub&&<form action={sendMessage}><input type="hidden" name="recipient" value={m.sender_id}/><label>Responder<input name="body" required maxLength={2000}/></label><button>Enviar</button></form>}</div>)}</section>
 {canManage&&<section id="config" className="card"><h2>Configuración</h2><p>Estos datos aparecen únicamente a estudiantes con sesión activa.</p><form action={saveSettings}><label>Banco<input name="bank_name" defaultValue={config.bank_name}/></label><label>Número de cuenta<input name="bank_account" defaultValue={config.bank_account}/></label><label>Titular<input name="bank_holder" defaultValue={config.bank_holder}/></label><label>Enlace privado de WhatsApp<input name="whatsapp_group" type="url" defaultValue={config.whatsapp_group}/></label><button>Guardar configuración</button></form></section>}
 </div></main>}
