import {redirect} from 'next/navigation';import Link from 'next/link';import {viewer} from '@/lib/supabase';import {completeLesson,sendMessage,signOut} from '@/app/actions';import TransferForm from '@/components/TransferForm';import PayPalButton from '@/components/PayPalButton';
export const dynamic='force-dynamic';
export default async function Dashboard({searchParams}:{searchParams:Promise<{course?:string}>}){
 const {db,user,profile}=await viewer();if(!user)redirect('/login?next=/dashboard');const params=await searchParams;
 const [{data:enrollments},{data:pending},{data:support},{data:messages},{data:settings}]=await Promise.all([
 db.from('enrollments').select('id,course_id,status,starts_at,expires_at,courses(id,title,slug,description)').eq('user_id',user.sub),
 db.from('bank_transfers').select('id,course_id,status,created_at').eq('user_id',user.sub).order('created_at',{ascending:false}),
 db.from('profiles').select('id,full_name').in('role',['support','admin','super_admin']).limit(1),
 db.from('messages').select('id,body,created_at,sender_id').or(`sender_id.eq.${user.sub},recipient_id.eq.${user.sub}`).order('created_at',{ascending:false}).limit(20),
 db.from('settings').select('key,value').in('key',['bank_name','bank_account','bank_holder','whatsapp_group'])
 ]);
 const active=(enrollments||[]).filter(e=>e.status==='active'&&(!e.expires_at||new Date(e.expires_at)>new Date()));
 const courseIds=active.map(e=>e.course_id);const {data:modules}=courseIds.length?await db.from('modules').select('id,title,course_id,position').in('course_id',courseIds).order('position'): {data:[]};
 const moduleIds=modules?.map(m=>m.id)||[];const {data:lessons}=moduleIds.length?await db.from('lessons').select('id,title,module_id,video_url,body,position').in('module_id',moduleIds).eq('published',true).order('position'):{data:[]};
 const {data:progress}=lessons?.length?await db.from('lesson_progress').select('lesson_id').eq('user_id',user.sub).in('lesson_id',lessons.map(l=>l.id)):{data:[]};
 const completed=new Set(progress?.map(p=>p.lesson_id));const chosen=lessons?.find(l=>!completed.has(l.id))||lessons?.[0]||null;const chosenModule=chosen?modules?.find(m=>m.id===chosen.module_id):null;const chosenCourse=chosenModule?active.find(e=>e.course_id===chosenModule.course_id)?.courses as unknown as {slug:string}|null:null;
 const selected=params.course?await db.from('courses').select('id,title,price,paypal_usd_price').eq('id',params.course).eq('published',true).single():null;
 const bank=Object.fromEntries((settings||[]).map(x=>[x.key,x.value]));
 return <main className="shell layout"><aside className="sidebar"><a href="#resumen">Resumen</a><a href="#cursos">Mis cursos</a><a href="#comunidad">Comunidad</a><a href="#pagos">Pagos</a><a href="#mensajes">Soporte</a>{['super_admin','admin','support','instructor'].includes(profile?.role)&&<Link href="/admin">Administración</Link>}<form action={signOut}><button className="ghost">Salir</button></form></aside><div className="dashboard stack"><div id="resumen"><span className="eyebrow">Mi espacio</span><h1 style={{fontSize:42}}>Hola, {profile?.full_name||profile?.email?.split('@')[0]||'estudiante'}.</h1><p>Sigue tus clases y consulta tus accesos.</p></div><div className="stats"><div className="card stat"><span className="meta">Cursos activos</span><strong>{active.length}</strong></div><div className="card stat"><span className="meta">Clases completadas</span><strong>{completed.size}</strong></div><div className="card stat"><span className="meta">Mensajes</span><strong>{messages?.length||0}</strong></div></div>{chosen&&chosenCourse&&<div className="card"><span className="eyebrow">Continúa aprendiendo</span><h2>{chosen.title}</h2><p>{chosenModule?.title}</p><Link className="button" href={`/curso/${chosenCourse.slug}/leccion/${chosen.id}`} target="_blank" rel="noreferrer">Ir a la clase</Link></div>}
 <section id="cursos"><div className="section-head"><h2>Mis cursos</h2><Link href="/cursos">Ver catálogo →</Link></div>{!enrollments?.length&&<div className="card"><p>Aún no tienes cursos asignados.</p><Link className="button ghost" href="/cursos">Explorar cursos</Link></div>}{enrollments?.map(e=>{const c=e.courses as unknown as {title:string,slug:string}|null;const valid=e.status==='active'&&(!e.expires_at||new Date(e.expires_at)>new Date());return <div className="card" key={e.id} style={{marginBottom:12}}><div className="row"><div><h3>{c?.title||'Curso'}</h3><span className={'badge '+(valid?'':'dim')}>{valid?'Activo':'Acceso vencido o suspendido'}</span></div><span className="meta">{e.expires_at?'Hasta '+new Date(e.expires_at).toLocaleDateString('es-DO'):'Sin caducidad'}</span></div>{valid&&c&&<><hr className="divider"/><Link className="button" href={`/curso/${c.slug}`}>Abrir curso y ver módulos</Link></>}</div>})}</section>
 {selected?.data&&!active.some(e=>e.course_id===selected.data!.id)&&<section id="pagos" className="card"><span className="eyebrow">Solicitud de acceso</span><h2>{selected.data.title}</h2><p>Importe: RD$ {Number(selected.data.price).toLocaleString('es-DO')}. Realiza la transferencia a los datos indicados y adjunta tu comprobante.</p>{bank.bank_name&&bank.bank_account&&bank.bank_holder?<><p><b>{bank.bank_name}</b><br/>Cuenta: {bank.bank_account}<br/>Titular: {bank.bank_holder}</p><TransferForm courseId={selected.data.id} price={Number(selected.data.price)} userId={user.sub}/></>:<div className="notice warning">Los datos bancarios todavía no están configurados. Contacta a soporte.</div>}{selected.data.paypal_usd_price&&<div style={{marginTop:22}}><PayPalButton courseId={selected.data.id} amount={Number(selected.data.paypal_usd_price)}/></div>}</section>}
 <section id="comunidad" className="card"><h2>Comunidad privada</h2>{active.length&&bank.whatsapp_group?<a className="button" href={bank.whatsapp_group} target="_blank" rel="noreferrer">Entrar al grupo de WhatsApp</a>:<p>El enlace aparecerá cuando tengas acceso activo y el administrador lo configure.</p>}</section>
 <section id="mensajes" className="card"><h2>Soporte</h2>{messages?.map(m=><p key={m.id} className="card"><b>{m.sender_id===user.sub?'Tú':'Soporte'}: </b>{m.body}<br/><small className="muted">{new Date(m.created_at).toLocaleString('es-DO')}</small></p>)}{support?.[0]?<form action={sendMessage}><input type="hidden" name="recipient" value={support[0].id}/><label>Escribe a soporte<textarea name="body" required maxLength={2000} rows={3}/></label><button>Enviar mensaje</button></form>:<p>El canal de soporte estará disponible cuando se asigne un administrador.</p>}</section>
 {pending?.length?<section><h2>Comprobantes enviados</h2>{pending.map(t=><p key={t.id} className="card">{new Date(t.created_at).toLocaleDateString('es-DO')} · {t.status}</p>)}</section>:null}</div></main>
}
